service: grouperDXPassthrough

frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-west-2
  environment:
    GROUPER_HOST: ${env:GROUPER_HOST}
    GROUPER_USERNAME: ${env:GROUPER_USERNAME}
    GROUPER_PASSWORD: ${env:GROUPER_PASSWORD}
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET_ID_A}
      - ${env:SUBNET_ID_B}
      - ${env:SUBNET_ID_C}

functions:
  hasMember:
    handler: ./src/index.hasMember

custom:
  webpack:
    includeModules: true
